HOME_ROUTE = "/"
IMPORT_EXPORT_ROUTE = "/import-export"
SETTINGS_ROUTE = "/settings"
INFO_ROUTE = "/info"
CREATE_SET_ROUTE = "/create-set"
SET_EDIT_ROUTE = "/set/edit"
SET_LEARN_ROUTE = "/set/learn"
SET_LEARN_SESSION_ROUTE = "/set/learn/session"
SEARCH_ROUTE = "/search"

DRAWER_ROUTES = [HOME_ROUTE, IMPORT_EXPORT_ROUTE, SETTINGS_ROUTE, INFO_ROUTE]
DEEP_ROUTES = [CREATE_SET_ROUTE, SET_EDIT_ROUTE, SET_LEARN_ROUTE, SET_LEARN_SESSION_ROUTE, SEARCH_ROUTE]
KNOWN_ROUTES = DRAWER_ROUTES + DEEP_ROUTES

ROUTE_TO_DRAWER_INDEX = {route: index for index, route in enumerate(DRAWER_ROUTES)}
