[project]
name = "Learning app"
version = "1.0.0"
description = "My first Flet larger project"
authors = [
  {name = "Bartosz Kogutowicz", email = "kogutek102s@gmail.com"}
]
dependencies = ["flet>=0.27.4", "pandas==2.2.2"]