"""TTS provider contract and error types.

UI and ``TtsService`` depend only on ``TtsProvider``. Swap ``GttsProvider``
for ElevenLabs or OpenAI later without changing cache or playback.
"""

from abc import ABC, abstractmethod


class TtsError(Exception):
    """Raised when speech cannot be synthesized."""


class TtsNetworkError(TtsError):
    """Raised when a provider cannot reach its remote API."""


class TtsProvider(ABC):
    """Backend that turns text into MP3 bytes.

    ``name`` and ``voice`` are part of the on-disk cache key so a later
    provider does not replay audio generated by an older one.
    """

    name: str
    voice: str = ""

    @abstractmethod
    async def synthesize(self, text: str, language: str) -> bytes:
        """Return MP3 bytes for ``text`` spoken in ``language``.

        Args:
            text: Already-normalized phrase to speak.
            language: IETF language tag such as ``en`` or ``pl``.

        Returns:
            MP3 audio bytes.

        Raises:
            TtsNetworkError: The remote service could not be reached.
            TtsError: Synthesis failed for another reason.
        """
