DEFAULT_APPBAR_HEIGHT = 100
DEFAULT_BOTTOM_APPBAR_HEIGHT = 80

CONTENT_MAX_WIDTH = 720
BODY_WIDTH_RATIO = 0.87
FORM_WIDTH_RATIO = 0.8
SETTINGS_WIDTH_RATIO = 0.7

BREAKPOINT_COMPACT = 600
BREAKPOINT_WIDE = 900

DEEP_FORM_VERTICAL_INSET = 52

DEFAULT_VIEWPORT_WIDTH = 500
DEFAULT_VIEWPORT_HEIGHT = 900

# Field width as a fraction of form_width (learn menu + session).
LEARN_WORDS_FIELD_WIDTH_RATIO = 0.90
LEARN_WORDS_FIELD_WIDTH_RATIO_WINDOWS = 0.83
LEARN_DEFINITION_FIELD_WIDTH_RATIO = 0.90
LEARN_DEFINITION_FIELD_WIDTH_RATIO_WINDOWS = 0.80
LEARN_DEFINITION_CHECK_BUTTON_SCALE = 1.3
